spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cobkludjm4es739r7j60-a.singapore-postgres.render.com:5432/b2bdoc_db
    username: b2bdoc_db_user
    password: uRWUApKZAgdx6Ekg6chegfQRvE17jHPp
  #    url: jdbc:postgresql://178.128.52.39:5432/digital_asset_db
  #    username: sovita
  #    password: Sovita#28
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: b2b-document-v4
jwt:
  secret: b2b-document-v4
myAdmin:
  username: Admin
  password: DigitalAsset1@
server:
  port: 4545

# Swagger URL
# /swagger-ui/index.html/
