spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cobkludjm4es739r7j60-a.singapore-postgres.render.com:5432/b2bdoc_db
    username: b2bdoc_db_user
    password: uRWUApKZAgdx6Ekg6chegfQRvE17jHPp
  #    url: jdbc:postgresql://178.128.52.39:5432/digital_asset_db
  #    username: sovita
  #    password: Sovita#28
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    broker-url:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: b2b-document-v4
jwt:
  secret: b2b-document-v4
myAdmin:
  username: Admin
  password: DigitalAsset1@
server:
  port: 4545

base_url_img : http://localhost:4545/api/v1/files/view_image?fileName=
dashboard_url: http://localhost:4545/
file_path: src/main/resources/static/images

# Swagger URL
# /swagger-ui/index.html/
