spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://178.128.52.39:5432/b2bdoc_db
    username: sovita
    password: Sovita#28

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    broker-url:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: b2b-document-v4
jwt:
  secret: A0WEwEhf+UFp3tI2PM3TfxRNk4a4dr8L2AyXyxu/JqY=
myAdmin:
  username: Admin
  password: DigitalAsset1@
server:
  port: 4545

base_url_img : http://localhost:4545/api/v1/files/view_images?fileName=
dashboard_url: http://localhost:4545/
file_path: src/main/resources/static/images

#base_url_img : https://bizweb-doc.kosign.dev/api/v1/files/view_images?fileName=
#dashboard_url: https://bizweb-doc.kosign.dev/
#file_path: /home/was/bizweb_api/b2b_doc/srv/b2b_doc/images

API_URL: https://bizweb-api.kosign.dev

# Swagger URL
# /swagger-ui/index.html/
