name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pusher's name
        id: get_pusher_name
        run: echo "::set-output name=name::$(git log -1 --format='%an')"

      - name: Send notification to Telegram
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"chat_id": "-1002117315042", "text": "[${{ steps.get_pusher_name.outputs.name }}] has pushed new code to branch main in API. Please pull."}' \
            "https://api.telegram.org/bot6751474194:AAEONyKqL-lNA5HlbYu7q2wPlCL6zyPeraA/sendMessage"
