name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get pusher's name
      id: get_pusher_name
      run: echo "::set-output name=name::$(git log -1 --format='%an')"

    - name: Send notification
      if: github.ref == 'refs/heads/main'
      run: |
        curl -X POST \
          -d "chatId=-724413963" \
          -d "message=[${{ steps.get_pusher_name.outputs.name }}] has pushed new code to branch main in API. Please pull." \
          -H "Content-Type: application/json" \
          https://api.telegram.org/bot6751474194:AAEONyKqL-lNA5HlbYu7q2wPlCL6zyPeraA/sendMessage
